// Mocks generated by Mockito 5.4.6 from annotations
// in geosignal_sentinel/test/features/positioning/data/repositories/location_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:geosignal_sentinel/features/positioning/data/datasources/location_datasource.dart'
    as _i3;
import 'package:geosignal_sentinel/features/positioning/data/models/position_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePositionDto_0 extends _i1.SmartFake implements _i2.PositionDto {
  _FakePositionDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationDataSource extends _i1.Mock
    implements _i3.LocationDataSource {
  MockLocationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.PositionDto> getPositionStream({
    int? intervalMs = 1000,
    int? distanceFilterMeters = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, [], {
              #intervalMs: intervalMs,
              #distanceFilterMeters: distanceFilterMeters,
            }),
            returnValue: _i4.Stream<_i2.PositionDto>.empty(),
          )
          as _i4.Stream<_i2.PositionDto>);

  @override
  _i4.Future<_i2.PositionDto> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i4.Future<_i2.PositionDto>.value(
              _FakePositionDto_0(
                this,
                Invocation.method(#getCurrentPosition, []),
              ),
            ),
          )
          as _i4.Future<_i2.PositionDto>);

  @override
  _i4.Future<_i2.PositionDto?> getLastKnownPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getLastKnownPosition, []),
            returnValue: _i4.Future<_i2.PositionDto?>.value(),
          )
          as _i4.Future<_i2.PositionDto?>);

  @override
  _i4.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
